### PR TITLE
Sorry, improved the script.

### PR DESCRIPTION
**Pull request by davepwsmith**

### CODE REVIEW

**Comment by retorquere** [comment]
Will this work for the Firefox plugin, or only Zotero standalone? I could add a test URL that wouldn't pop up the picker.

**Comment by davepwsmith** [comment]
It seems to work for both on my computer, but it might be because I have standalone installed. A test URL would work fine, this also works, but it's a little hackish:
``` applescript
﻿set zotRunning to do shell script "/usr/bin/curl http://localhost:23119/better-bibtex/collection"
if zotRunning is "No endpoint found" then
	display alert "This script will not work unless Zotero is running. Please launch Zotero and try again"
	tell application "Scrivener"
		activate
	end tell
	error number -128
else if zotRunning is "Could not export bibliography: no path" then
	
	do shell script "/usr/bin/curl http://localhost:23119/better-bibtex/cayw?format=pandoc | pbcopy"
	tell application "Scrivener"
		activate
		repeat until application "Scrivener" is frontmost
		end repeat
		tell application "System Events"
			keystroke "v" using command down
		end tell
		do shell script "/usr/bin/pbcopy < /dev/null"
	end tell
end if
````

**Comment by retorquere** [comment]
I don't know under what circumstances applescript reports positively for 

```
application id "org.zotero.zotero" is running
```

but I'm doubtful it would detect firefox-running-zotero, as it will identify as application firefox, not org.zotero. Should be easy to test though -- just stop ZSA, start FF+Zotero (if you have it), and see what it does. 

The next release will have `http://localhost:23119/better-bibtex/cayw?probe=probe`, documentation on the site has already been adapted for it. But the above is over-determined; if you call `http://localhost:23119/better-bibtex/collection` with Zotero not running, you won't get "No endpoint found" but an http failure; getting "No endpoint found" actually means Zotero *is* running, but it doesn't have BBT installed (which incidentally means that the probe url will allow detection of this, as it will yield the same message).

**Comment by davepwsmith** [comment]
Right, so it's slightly more complicated than that it seems!
`application id "org.zotero.zotero is running` only works for standalone zotero; if Firefox is running with Zotero-Firefox OPEN then `curl http://localhost:23119/better-bibtex/collection` returns `Could not export bibliography: no path`; if Firefox is running but with Zotero-Firefox CLOSED then `curl http://localhost:23119/better-bibtex/collection` returns `No endpoint found`; only if both Zotero Standalone and Firefox (the browser itself) are closed does it return an http failure.

**Comment by davepwsmith** [comment]
Actually, the only circumstance in which you get `No endpoint found` is if you:
1. Load firefox
2. Load Zotero Standalone
3. Quit Zotero Standalone
4. Make the http call.

A successful call also minimizes firefox, which is kind of annoying, but I think you said you'd fix that in the next release.

**Comment by retorquere** [comment]
If you load both ZSA and FF+Zotero, FF+Zotero goes into a kind of slave mode. This mode is not yet supported by BBT, although it may sometimes work.

1.2.39 has just been released, see new documentation on the cayw page.

**Comment by retorquere** [comment]
The "No endpoint" in the previous scenario means that Firefox has Zotero in stalled but not BBT. I think for the most part having FF+Zotero in slave mode that way should work. Installing BBT in both yields unpredictable errors as BBT isn't hip with their undocumented IPC mechanism they use to talk between the two, and both copies will try to open the same database (one will lose, and that instance will start throwing errors).

**Comment by davepwsmith** [comment]
`/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe'` throws up the search box I'm afraid.

**Comment by retorquere** [comment]
try `/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?probe=probe`. Empty values are counted as not-present.

**Comment by davepwsmith** [comment]
Is there any chance that it could be made to spit out a boolean 'true' or a 1 or a 0? The version number is going to change every time and make the script more difficult to sort out!

**Comment by retorquere** [comment]
I've changed it so it'll report "ready", but in the interim, these responses can be counted on:

Zotero Yes, BBT No: "No endpoint found"
Zotero No: error
Zotero Yes, BBT Yes: anthing else

**Comment by davepwsmith** [comment]
OK so this will work for all cases:
```applescript
set zotRunning to do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/probe=probe' 2>/dev/null; exit 0"
if zotRunning is "" then
	display alert "This script will not work unless Zotero is running. Please launch Zotero and try again"
	tell application "Scrivener"
		activate
	end tell
	error number -128
else if zotRunning is "No endpoint found" then
	display alert "This script will not work unless Better BibTeX is installed. Please make sure that Better BibTeX is installed in the running instance of Zotero"
	tell application "Scrivener"
		activate
	end tell
	error number -128
else if zotRunning is "ready" then
	do shell script "/usr/bin/curl http://localhost:23119/better-bibtex/cayw?format=pandoc | pbcopy"
	tell application "Scrivener"
		activate
		repeat until application "Scrivener" is frontmost
		end repeat
		tell application "System Events"
			keystroke "v" using command down
		end tell
		do shell script "/usr/bin/pbcopy < /dev/null"
	end tell
end if
```
Applescript chokes on errors rather than reporting them, so errors are redirected to /dev/null, and an error just throws blank output.

**Comment by retorquere** [comment]
The "ready" will be in 1.3.0, build is running.

**Comment by retorquere** [comment]
1.3.0 is out and docs have been updated

**Pull request merged**
