### PR TITLE
Edits to applescript implementations

### PR DESCRIPTION
**Pull request by davepwsmith**
Added my own pics for DIY applescript bundles because it seemed easier
than trawling stackedit.

Moved my source & binaries to github, and added a binary for each
relevant output format (pandoc, mmd, scannable-cites).

Edited the line about removing autopaste to something which would work!

### CODE REVIEW

**Comment by retorquere** [comment]
Splendid (or awesome, depending on which side of the water you live). I honestly like your instructions a whole lot better -- so much better in fact that, with your permission, I'd rather just delete all the scrivener/marked  stuff from the cayw page and just link to that page.

**Comment by davepwsmith** [comment]
Fine by me.

**Comment by retorquere** [comment]
So just to be clear, I'd link to http://davepwsmith.github.io/academic-scrivener-howto/, right?

**Comment by davepwsmith** [comment]
That's the one. The gh-pages was more readable than just the repo with a readme.md 

On 2 September 2015 14:42:58 BST, retorquere <notifications@github.com> wrote:
>So just to be clear, I'd link to
>http://davepwsmith.github.io/academic-scrivener-howto/, right?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ZotPlus/ZotPlus.github.io/pull/5#issuecomment-137086112

--
https://keybase.io/davidsmith
--
Sent from my phone. Please excuse my brevity.

**Comment by retorquere** [comment]
(BTW technically it is not the BBT picker; BBT just convinces Zotero to show its picker and grabs the results. The picker is wholly the work of the Zotero team -- I just exposed it through an URL and format the references)

**Comment by retorquere** [comment]
Done. Much better this way, I don't use Scrivener myself so my description will never be as good as those from someone who does.

**Comment by retorquere** [comment]
Oh and BTW BBT can also export Pandoc CSL JSON, which I've been led to believe is pandocs "native" bibliography format.

**Comment by retorquere** [comment]
Do you happen to know if/how marked handles latex embedded in markdown?

**Comment by davepwsmith** [comment]
> Done. Much better this way, I don't use Scrivener myself so my description will never be as good as those from someone who does.

Indeed, it's a pretty specialised tool and I'm using it in a way which is far from what it was designed for, so it's a bit of an edge case!

> Oh and BTW BBT can also export Pandoc CSL JSON, which I've been led to believe is pandocs "native" bibliography format.

I believe it is, but pandoc handles bib(la)tex pretty flawlessly, and it's more useful to have a .bib file lying around than a file that only Pandoc can use. It's also much easier to manually edit a .bib file than pandoc's JSON behemoths.

> Do you happen to know if/how marked handles latex embedded in markdown?

Badly I should think, unless you use Pandoc as a processor, in which case it gets ignored.

**Comment by davepwsmith** [comment]
To clarify, Marked app doesn't process any markdown itself, so it depends on how the markdown processor you instruct it to use (default is multimarkdown or discount) handles it.

**Comment by retorquere** [comment]
I see. I'll have to give that a go. I'm actually surprised there is any speed difference between them -- once cached, they should behave (almost?) exactly the same.

**Pull request merged**
